version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6378:6378'
    command: redis-server --save 20 1 --loglevel warning
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cf2ea05574efd3caed6f
      - POSTGRES_DB=micalli
    ports:
      - '5435:5435'
